name: Runway
description: "Support MiniMessage formatting everywhere from anywhere."
version: '${version}'
main: me.mrafonso.runway.Runway
api-version: '1.21'
author: MrAfonso
loader: me.mrafonso.runway.RunwayLoader
open-classloader: true
folia-supported: true
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    MiniPlaceholders:
      load: BEFORE
      required: false
      join-classpath: true
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: true
    ViaBackwards:
      load: BEFORE
      required: false
      join-classpath: true
    ViaRewind:
      load: BEFORE
      required: false
      join-classpath: true